apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-devops-deployment
  label: react-devops
spec:
  selector:
    matchLabels:
      app: react-devops
  replicas: 2
  template:
    metadata:
      labels:
        app: react-devops
    spec:
      containers:
        - name: react-devops
          image: habhi/react_devops:latest
          ports:
            - containerPort: 3000