apiVersion: v1
kind: Service
metadata:
  name: react-devops-service
  namespace: default
spec:
  selector:
    app: {{ .Values.metadata.labels.app}}
  ports:
    - name: tcp
      port: 80
      targetPort: 80
  type: {{ .Values.spec.type}}